#ifndef UGOMEMO_PPM_CONSTANTS_H_
#define UGOMEMO_PPM_CONSTANTS_H_

// All in bytes
#define PPM_FILE_HEADER_SIZE 0x10
#define PPM_META_SIZE 0x90
#define PPM_META_OFFSET PPM_FILE_HEADER_SIZE
#define PPM_SOUND_HEADER_SIZE 0x20
#define PPM_ANIM_HEADER_SIZE 0x08
#define PPM_ANIM_HEADER_OFFSET (PPM_THUMBNAIL_OFFSET + PPM_THUMBNAIL_SIZE)
#define PPM_THUMBNAIL_SIZE 0x600
#define PPM_THUMBNAIL_OFFSET 0xA0
#define PPM_FSID_LENGTH 8
#define PPM_FILENAME_LENGTH 18
#define PPM_FILENAME_FRAGMENT_LENGTH 8

#define PPM_FRAME_WIDTH          256
#define PPM_FRAME_HEIGHT         192

#define PPM_THUMBNAIL_WIDTH       64
#define PPM_THUMBNAIL_HEIGHT      48
#define PPM_THUMB_PIXEL_COUNT  (PPM_THUMBNAIL_HEIGHT * PPM_THUMBNAIL_WIDTH)
#define PPM_THUMB_SIZE_BYTES   (PPM_THUMB_PIXEL_COUNT * 3)

#define PPM_STEP_INDEX_MIN         0
#define PPM_STEP_INDEX_MAX        88
#define PPM_PREDICTOR_MIN     -32768
#define PPM_PREDICTOR_MAX      32767
#define PPM_SCALING_FACTOR        16  /* 16 bits per sample in the output of decoding. */
#define PPM_AUDIO_SAMPLE_RATE   8192

#define PPM_LAYER_SIZE (PPM_FRAME_WIDTH * PPM_FRAME_HEIGHT)

#define PPM_SIGNATURE_SIZE 128

// Rendered string length in bytes without null terminator
#define PPM_FILENAME_STR_LENGTH 24  // F78DA8_14768882B56B8_030

#endif
